config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'

  get    '/session/new',   to: 'session#new'
  post   '/session',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'
  get   '/sales/shop', to: 'sales#new'
  post '/sales/dates', to: 'sales#total'
  get '/sales/dates.json', to: 'sales#total'
  get '/sales/dates', to: 'sales#total'
  root 'orders#index'
  resources :order_items do
    member do
      get :line_calc
    end
  end
  resources :menu_items
  resources :orders do
    member do
      get :price_calc
      get :line_calc
    end
  end
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :orders

  def sales_range (start_date, end_date)
    emp_orders = Order.where(:created_at => start_date..end_date, :employee_id => id)
    emp_orders.map(&:subtotal).sum.round(2)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.orders.each {|ord| ord.employee_id = 0}
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :position, :password, :payscale)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employee_name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= collection_select(:employee, :position, ['Employee', 'Manager'], :to_str, :to_str, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :employee_password %>
  </div>

  <div class="field">
    <%= form.label :payscale %>
    <%= form.text_field :payscale, id: :employee_payscale %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Password</th>
      <th>Payscale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.position %></td>
        <td><%= employee.password %></td>
        <td><%= employee.payscale %></td>
        <%  if current_emp.position == 'Manager' %>
          <td><%= link_to 'Show', employee %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<% if (current_emp != @employee && current_emp.position != "Manager") %>
     <script>window.location.href="/employees"</script>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employee.position %>
</p>

<p>
  <strong>Password:</strong>
  <%= @employee.password %>
</p>

<p>
  <strong>Payscale:</strong>
  <%= @employee.payscale %>
</p>

<p>
  <strong>Daily Sales:</strong>
  <%= @employee.sales_range(Date.yesterday, Date.today) %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>