config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'

  get    '/session/new',   to: 'session#new'
  post   '/session',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'
  get   '/sales/shop', to: 'sales#new'
  post '/sales/dates', to: 'sales#total'
  get '/sales/dates.json', to: 'sales#total'
  get '/sales/dates', to: 'sales#total'
  root 'orders#index'
  resources :order_items do
    member do
      get :line_calc
    end
  end
  resources :menu_items
  resources :orders do
    member do
      get :price_calc
      get :line_calc
    end
  end
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :employee
  has_many :order_items
  has_many :menu_items, through: :order_items
  accepts_nested_attributes_for :order_items, allow_destroy: true

after_save :update_totals

  def update_totals
    sub = calc_sub
    update_columns(subtotal: sub)
    tx = calc_taxes
    tot = calc_total
    update_columns(tax: tx, total: tot)
  end

  def calc_sub
   order_items.map(&:line_total).sum.round(2)
  end

  def calc_taxes
    (subtotal * 0.1).round(2)
  end

  def calc_total
    (subtotal + calc_taxes).round(2)
    end

  def sales_range (start_date, end_date)
    sales = Order.where(:created_at => start_date..end_date)
    sales.map(&:sub_total).sum.round(2)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :price_calc]

  def price_calc
    respond_to do |format|
      print("test")
      val1 = params[:menu_item_id]
      val2 = params[:quantity]

      print("test")
      format.json {render json: @order, methods: [:calc_sub, :calc_taxes, :calc_total], only: []}
    end
  end
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.subtotal = 0
      @order.order_items.build
  end


  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer, :subtotal, :tax, :total, :employee_id, :order_items_attributes => [:menu_item_id, :id, :quantity])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer %>
    <%= form.text_field :customer, id: :order_customer %>
  </div>

  <div class="field" >
    <%= form.label :employee_id %>
    <%= collection_select(:order, :employee_id, Employee.all, :id, :name, prompt: true, :selected => current_emp.id) %>
  </div>

  <div class="field">
    <p>Choose the items for your order:</p>
    <%= form.fields_for :order_items do |item| %>
      <p>
        <%= item.collection_select :menu_item_id, MenuItem.all, :id, :name %>
        <%= item.collection_select :menu_item, MenuItem.all, :id, :price, {:include_blank => false}, {:disabled => "disabled", :id => "sel", :value => '1'} %>
        <%= item.number_field :quantity, id: :order_item_quantity %>
      </p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :subtotal %>
    <span id="subt">$0.00</span>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <span id="tx">$0.00</span>
  </div>

  <div class="field">
    <%= form.label :total %>
    <span id="tot">$0.00</span>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

  <script>
      jQuery(function () {
          jQuery("#order_order_items_attributes_0_menu_item_id").change(function () {
              console.log(jQuery(this).val());
              document.getElementById('sel').value = jQuery(this).val();
          });
      });
      jQuery(function () {
          jQuery("#order_order_items_attributes_0_menu_item_id").change(function () {
                  var sub = (document.getElementById('sel')
                  .options[document.getElementById('sel').selectedIndex]
                  .innerHTML) * document.getElementById('order_item_quantity').value;
              document.getElementById('subt').innerHTML = ("$" + sub.toFixed(2));
              document.getElementById('tx').innerHTML = ("$" + (sub * 0.1).toFixed(2));
              document.getElementById('tot').innerHTML = ("$" + (sub * 1.1).toFixed(2));
          });
      });
      jQuery(function () {
          jQuery("#order_item_quantity").change(function () {
              var sub = (document.getElementById('sel')
                  .options[document.getElementById('sel').selectedIndex]
                  .innerHTML) * document.getElementById('order_item_quantity').value;
              document.getElementById('subt').innerHTML = ("$" + sub.toFixed(2));
              document.getElementById('tx').innerHTML = ("$" + (sub * 0.1).toFixed(2));
              document.getElementById('tot').innerHTML = ("$" + (sub * 1.1).toFixed(2));
          });
      });
  </script>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Subtotal</th>
      <th>Tax</th>
      <th>Total</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer %></td>
        <td><%= order.subtotal %></td>
        <td><%= order.tax %></td>
        <td><%= order.total %></td>
        <td><%= order.employee.name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @order.subtotal %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @order.tax %>
</p>

<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @order.employee.name %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>