config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'

  get    '/session/new',   to: 'session#new'
  post   '/session',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'
  get   '/sales/shop', to: 'sales#new'
  post '/sales/dates', to: 'sales#total'
  get '/sales/dates.json', to: 'sales#total'
  get '/sales/dates', to: 'sales#total'
  root 'orders#index'
  resources :order_items do
    member do
      get :line_calc
    end
  end
  resources :menu_items
  resources :orders do
    member do
      get :price_calc
      get :line_calc
    end
  end
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item

  after_save :decrement_inventory

  def decrement_inventory
    count = menu_item.inventory - quantity
    menu_item.update_inventory(count)
  end
  def line_total
    if menu_item.nil?
      return 0
    else
      menu_item.price * quantity
    end
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: [:show, :edit, :update, :destroy, :line_calc]

  def line_calc
    @order.order_items.menu_item_id = params[:menu_item_id]
    @order.order_items.quantity = params[:quantity]
    respond_to do |format|
      format.json {render json: @order_item, methods: [:line_total], only: [] }
    end
  end
  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1
  # GET /order_items/1.json
  def show
  end

  # GET /order_items/new
  def new
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
    @order_item = OrderItem.new(order_item_params)
    respond_to do |format|
      if @order_item.save
        format.html { redirect_to @order_item, notice: 'Order item was successfully created.' }
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to @order_item, notice: 'Order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:order_id, :menu_item_id, :quantity)
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<%= form_with(model: order_item, local: true) do |form| %>
  <% if order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= collection_select(:order_item, :order_id, Order.all, :id, :customer, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :menu_item_id %>
    <%= collection_select(:order_item, :menu_item_id, MenuItem.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :order_item_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Menu item</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.order.customer %></td>
        <td><%= order_item.menu_item.name %></td>
        <td><%= order_item.quantity %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order.customer %>
</p>

<p>
  <strong>Menu item:</strong>
  <%= @order_item.menu_item.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>